# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Dhaba',
        ),
    ]
