# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180516_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dhaba',
            new_name='RestaurantLocation',
        ),
    ]
