# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180516_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='data_time_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
