# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20180516_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='data_time_field',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
