# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20180516_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='data_time_field',
            field=models.PositiveIntegerField(),
        ),
    ]
