# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20180516_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='data_time_field',
            new_name='number',
        ),
    ]
