# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20180516_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='number',
        ),
    ]
