# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_delete_menucard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='year_in_school',
        ),
    ]
