# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
