# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_delete_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time will be recorded automatically'),
        ),
    ]
