# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20180517_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='name',
            field=models.CharField(help_text='Mandatory', max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
